feat: save tag when itil obj is closed
pluginsGLPI/tag pull request #172
Opened 2024-01-17 08:32 UTC by Rom1-B

Enable tags to be modified on closed tickets.
The tags field was already editable, but the save button was not visible, so the modification could not be saved. 
Now, as soon as a tag is added or removed, it is immediately saved in AJAX.

2024-01-17 10:48 UTC, stonebuzz approved these changes

2024-01-18 08:27 UTC, AdrienClairembault requested changes
Functional review: looks good but we should probably set `window.glpiUnsavedFormChanges = false` after the tags are updated to avoid the unsaved changes warning when trying to leave the page.

2024-01-18 08:39 UTC, AdrienClairembault requested changes

2024-01-18 08:39 UTC, AdrienClairembault commented on ajax/tag.php
> +            __('Tag has been updated'),
Maybe this would be more precise as we can have multiple tags on a ticket ?

```suggestion
            __('Tags have been updated'),
```

2024-01-18 08:39 UTC, AdrienClairembault commented on ajax/tag.php
> +            __('Tag has not been updated'),
```suggestion
            __('Tags have not been updated'),
```

2024-01-22 12:12 UTC, AdrienClairembault requested changes

2024-01-22 12:12 UTC, AdrienClairembault commented on inc/tag.class.php
> +                        window.location.reload();
I think we should avoid reloading the page if the update is done using AJAX.

2024-01-22 13:03 UTC, AdrienClairembault approved these changes

2024-01-22 13:18 UTC, cedric-anne commented on ajax/tag.php
> +            __('Tags have been updated'),
```suggestion
            __('Tags have been updated', 'tag'),
```

2024-01-22 13:18 UTC, cedric-anne commented on ajax/tag.php
> +            __('Tags have not been updated'),
```suggestion
            __('Tags have not been updated', 'tag'),
```

2024-01-22 13:18 UTC, cedric-anne commented on ajax/tag.php
> +        __('Missing parameters'),
```suggestion
        __('Missing parameters', 'tag'),
```

2024-01-22 13:18 UTC, cedric-anne approved these changes

2024-02-02 10:47 UTC, AdrienClairembault approved these changes

2024-02-20 16:03 UTC, merged