See Tag Only On Active Itemtypes
pluginsGLPI/tag pull request #221
Opened 2024-12-19 10:56 UTC by tsmr

- [X ] I have performed a self-review of my code.
- [X ] I have added tests (when available) that prove my fix is effective or that my feature works.

## Description

By design you will see Tag dropdown on all objects, but in fact you nee to display the dropdown only on itemtypes with active tag

2024-12-20 07:47 UTC, Rom1-B requested changes

2024-12-20 07:47 UTC, Rom1-B commented on inc/tag.class.php
> +        return !empty($itemtype) && class_exists($itemtype) && !in_array($itemtype, self::getBlacklistItemtype()) && ($use_global_tag == true ? $use_global_tag : in_array($itemtype, $types_menu));
Just to simplify reading:
```suggestion
        return !empty($itemtype) &&
            class_exists($itemtype) &&
            !in_array($itemtype, self::getBlacklistItemtype()) &&
            ($use_global_tag || in_array($itemtype, $types_menu));
```

2024-12-20 08:05 UTC, stonebuzz commented on inc/tag.class.php
> +        return !empty($itemtype) && class_exists($itemtype) && !in_array($itemtype, self::getBlacklistItemtype()) && ($use_global_tag == true ? $use_global_tag : in_array($itemtype, $types_menu));
suggestion 

```php
public static function canItemtype($itemtype = '')
{
    if (empty($itemtype) || !class_exists($itemtype) || in_array($itemtype, self::getBlacklistItemtype())) {
        return false;
    }

    $tags = new self();
    $types_menu = [];
    $use_global_tag = false;

    foreach ($tags->find(['is_active' => 1]) as $tag) {
        if (!empty($tag['type_menu'])) {
            $types_menu = array_merge($types_menu, json_decode($tag['type_menu']));
        } else {
            $use_global_tag = true;
        }
    }

    return $use_global_tag || in_array($itemtype, $types_menu);
}
```

2024-12-20 09:19 UTC, Rom1-B approved these changes

2024-12-20 09:19 UTC, stonebuzz commented
@tsmr 

can you try this

```php
public static function canItemtype($itemtype = '')
{
    if (empty($itemtype) || !class_exists($itemtype) || in_array($itemtype, self::getBlacklistItemtype())) {
        return false;
    }

    $tags = new self();
    $types_menu = [];
    $use_global_tag = false;

    foreach ($tags->find(['is_active' => 1]) as $tag) {
        if (!empty($tag['type_menu'])) {
            $types_menu = array_merge($types_menu, json_decode($tag['type_menu']));
        } else {
            $use_global_tag = true;
        }
    }

    return $use_global_tag || in_array($itemtype, $types_menu);
}
```

2024-12-26 08:13 UTC, stonebuzz approved these changes

2024-12-26 08:13 UTC, merged